# Generated by Django 5.0.3 on 2024-04-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='invite_code_u',
            new_name='invite_code',
        ),
    ]
