# Generated by Django 5.0.3 on 2024-04-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_invite_code_u_user_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Активированный инвайт-код'),
        ),
    ]
