version: '3'

services:
  django:
      env_file:
        - .env
      build:
        dockerfile: Dockerfile
      ports:
        - "8001:8000"
      command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      depends_on:
        - postgres

  postgres:
    image: postgres
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d $${POSTGRES_USER} -U $${POSTGRES_DB}' ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data: